arrowParens: "always"
bracketSameLine: false
bracketSpacing: true
endOfLine: lf
printWidth: 120
semi: true
singleQuote: true
tabWidth: 2
trailingComma: "all"
useTabs: true
overrides:
    - files: "*.ng.html"
      options:
        parser: "angular"
    - files: "*.html"
      options:
        parser: "html"

# https://prettier.io/docs/en/options.html